/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package source;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truong
 */
public class StudentManager extends javax.swing.JFrame {

    CheckData data = new CheckData();
    DefaultTableModel model = new DefaultTableModel();
    ConnectToSQL sql = new ConnectToSQL();
    int location = -1;

    /**
     * Creates new form StudentManager
     */
    public StudentManager() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        addColummiIndetifyTable();
        fillTable();

    }

    public boolean checkEmpty(JTextField a) {
        if (a.getText().isEmpty()) {
            a.setBackground(Color.yellow);
            return false;
        } else {
            a.setBackground(Color.white);
        }
        return true;
    }

    public boolean checkForm() {
        if (!checkEmpty(txtMaHoaDon)) {
            JOptionPane.showMessageDialog(this, "Vui long ma hoa don");
            return false;
        } else if (!data.checkID(txtMaHoaDon.getText())) {
            JOptionPane.showMessageDialog(this, "Nhap ma hoa don khong dung dinh dang");
            return false;
        } else if (!checkEmpty(txtMaHang)) {
            JOptionPane.showMessageDialog(this, "Vui long nhap ma hang");
            return false;
        } else if (!checkEmpty(txtDate)) {
            JOptionPane.showMessageDialog(this, "Khong duoc bo trong ngay mua");
            return false;
        } else if (!data.checkDate(txtDate.getText())) {
            JOptionPane.showMessageDialog(this, "Vui long nhap ngay sinh theo dinh dang (yyyy/mm/dd)");
            return false;
        } else if (!checkEmpty(txtTenHang)) {
            JOptionPane.showMessageDialog(this, "Khong duoc bo trong ten hang");
            return false;
        } else if (!checkEmpty(txtSoLuong)) {
            JOptionPane.showMessageDialog(this, "Vui long nhap so luong");
            return false;
        } else if (!data.CheckAmount(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Nhap so luong la so va lon hon 0");
            return false;
        } else if (!checkEmpty(txtDonGia)) {
            JOptionPane.showMessageDialog(this, "Vui long nhap don gia");
            return false;
        } else if (!data.CheckPrice(txtDonGia.getText())) {
            JOptionPane.showMessageDialog(this, "Nhap don gia  la so va lon hon 0");
            return false;
        }
        return true;
    }

    public List<Store> listData() {
        try {
            List<Store> list = sql.getAllData();
            return list;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public void addColummiIndetifyTable() {
        String[] column = {"MaHoaDon", "MaHang", "TenHang", "NgayMua", "SoLuong", "Dongia", "Thanh Tien"};
        model.setColumnIdentifiers(column);
        tblList.setModel(model);

    }

    public void fillTable() {
        List<Store> list = listData();
        model.setRowCount(0);
        list.forEach((sv) -> {
            model.addRow(new Object[]{sv.getMaHoaDon(), sv.getMaHang(), sv.getTenHang(), sv.getNgayMua(), sv.getSoluong(), sv.getDongia(), sv.getThanhtien()});
        });
        tblList.setModel(model);
    }

    public int mesage(String a) {
        return JOptionPane.showConfirmDialog(this, a, "Notifycation", JOptionPane.YES_NO_OPTION);
    }

    public void ShowForm(int a) {
        Store sv = listData().get(a);
        txtMaHoaDon.setText(sv.getMaHoaDon());
        txtMaHang.setText(sv.getMaHang());
        txtTenHang.setText(sv.getTenHang());
        txtDate.setText(sv.getNgayMua());
        txtSoLuong.setText(String.valueOf(sv.getSoluong()));
        txtDonGia.setText(String.valueOf(sv.getDongia()));
        txtThanhTien.setText(String.valueOf(sv.getThanhtien()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtMaHang = new javax.swing.JTextField();
        txtTenHang = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Store Manager");

        jLabel2.setText("Ma Hoa Don");

        jLabel3.setText("Ma Hang");

        jLabel4.setText("Ten Hang");

        jLabel5.setText("So Luong");

        jLabel6.setText("Don Gia");

        jLabel7.setText("Thanh Tien");

        txtThanhTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtThanhTienFocusLost(evt);
            }
        });

        jLabel8.setText("Ngay Mua");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDonGia)
                    .addComponent(txtThanhTien)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back-icon.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirst);

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-icon (1).png"))); // NOI18N
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel2.add(btnPre);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forward-icon (1).png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext);

        btnEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Next-icon.png"))); // NOI18N
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnd);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new-file-icon.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Text-Edit-icon.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-Close-icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setResizable(false);
            tblList.getColumnModel().getColumn(1).setResizable(false);
            tblList.getColumnModel().getColumn(2).setResizable(false);
            tblList.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!checkEmpty(txtMaHoaDon)) {
            JOptionPane.showMessageDialog(this, "Nhap ma hoa don muon xoa");
        } else if (!data.checkID(txtMaHoaDon.getText())) {
            JOptionPane.showMessageDialog(this, "Ma hoa don sai dinh dang");
        } else {
            try {
                if (mesage("Ban chat muon xoa hoa don nay khong") == JOptionPane.YES_OPTION) {
                    if (sql.delete(txtMaHoaDon.getText())) {
                        JOptionPane.showMessageDialog(this, "Xoa Thanh Cong");
                        fillTable();
                        btnNewActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xoa Khong Thanh Cong");
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (checkForm()) {
            try {
                Store sv = new Store();
                sv.setMaHoaDon(txtMaHoaDon.getText());
                sv.setMaHang(txtMaHang.getText());
                sv.setTenHang(txtTenHang.getText());
                sv.setNgayMua(txtDate.getText());
                sv.setSoluong(Integer.parseInt(txtSoLuong.getText()));
                sv.setDongia(Float.parseFloat(txtDonGia.getText()));
                sv.setThanhtien(Float.parseFloat(txtThanhTien.getText()));
                if (sql.findID(txtMaHoaDon.getText()) == null) {
                    if (sql.save(sv)) {
                        JOptionPane.showMessageDialog(this, "Luu Thanh Cong");
                        fillTable();
                        btnNewActionPerformed(evt);
                    } else {
                        JOptionPane.showMessageDialog(this, "That Bai");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Trung Ma Hoa don");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtMaHoaDon.setText("");
        txtMaHang.setText("");
        txtTenHang.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        txtThanhTien.setText("");
        txtDate.setText("");
        txtMaHang.setBackground(Color.white);
        txtTenHang.setBackground(Color.white);
        txtSoLuong.setBackground(Color.white);
        txtDonGia.setBackground(Color.white);
        txtDate.setBackground(Color.white);
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtThanhTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThanhTienFocusLost
        if (checkEmpty(txtDonGia) && checkEmpty(txtSoLuong)) {
            int soluong = Integer.parseInt(txtSoLuong.getText());
            float dongia = Float.parseFloat(txtDonGia.getText());
            double sum = soluong * dongia;
            if (sum >= 5000) {
                sum = sum * 0.9;
            }
            txtThanhTien.setText(String.valueOf(sum));

        }
    }//GEN-LAST:event_txtThanhTienFocusLost

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!checkEmpty(txtMaHoaDon)) {
            JOptionPane.showMessageDialog(this, "Nhap ma hoa don muon cap nhat");
        } else if (!data.checkID(txtMaHoaDon.getText())) {
            JOptionPane.showMessageDialog(this, "Ma hoa don sai dinh dang");
        } else {
            Store sv = new Store();
            sv.setMaHoaDon(txtMaHoaDon.getText());
            sv.setMaHang(txtMaHang.getText());
            sv.setTenHang(txtTenHang.getText());
            sv.setNgayMua(txtDate.getText());
            sv.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            sv.setDongia(Float.parseFloat(txtDonGia.getText()));
            sv.setThanhtien(Float.parseFloat(txtThanhTien.getText()));
            try {
                if (checkForm()) {
                    if (sql.findID(txtMaHoaDon.getText()) != null) {
                        if (mesage("Ban co chat muon cap nhat") == JOptionPane.YES_OPTION) {
                            if (sql.update(sv)) {
                                JOptionPane.showMessageDialog(this, "Cap nhat Thanh Cong");
                                fillTable();
                                btnNewActionPerformed(evt);
                            } else {
                                JOptionPane.showMessageDialog(this, "Cap nhat That Bai");
                            }
                        }
                    } else {
                        if (mesage("Sinh vien khong ton tai ban co muon them moi ") == JOptionPane.YES_OPTION) {
                            btnSaveActionPerformed(evt);
                        }
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        ShowForm(0);
        tblList.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        int lenght = listData().size() - 1;
        ShowForm(lenght);
        tblList.setRowSelectionInterval(lenght, lenght);

    }//GEN-LAST:event_btnEndActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        location--;

        if (location < 0) {
            location = listData().size() - 1;
        }
        ShowForm(location);
        tblList.setRowSelectionInterval(location, location);
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        location++;

        if (location > listData().size() - 1) {
            location = 0;
        }
        ShowForm(location);
        tblList.setRowSelectionInterval(location, location);
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        location = tblList.getSelectedRow();
        if (location != -1) {
            ShowForm(location);
        }
    }//GEN-LAST:event_tblListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
